version: '3.7'
services:
    docker:
        image: docker:dind
        environment:
            DOCKER_TLS_CERTDIR: /certs
        volumes:
            - /etc/docker/dind-daemon.json:/etc/docker/daemon.json:ro
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client
            - docker-data:/var/lib/docker
        networks:
            - traefik-public

    jenkins:
        image: hub.herman.team/jenkins:1
        environment:
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1
        volumes:
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        networks:
            - traefik-public
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.http.routers.jenkins.rule=Host(`jenkins.herman.team`)
                - traefik.http.routers.jenkins.entrypoints=https
                - traefik.http.routers.jenkins.service=jenkins
                - traefik.http.services.jenkins.loadbalancer.server.port=8080
                - traefik.http.routers.jenkins.tls=true
                - traefik.http.routers.jenkins.tls.certResolver=letsEncrypt
            mode: replicated
            replicas: 1
            update_config:
                parallelism: 1
            restart_policy:
                condition: on-failure
            placement:
                constraints: [node.role == manager]

volumes:
    jenkins-data:
    docker-certs:
    docker-data:

networks:
    traefik-public:
        external: true
