version: '3.7'
services:
    jenkins:
        image: ${REGISTRY}/jenkins:${IMAGE_TAG}
        environment:
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1
        volumes:
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        networks:
            - traefik-public
        deploy:
            labels:
                - traefik.enable=true
                - traefik.docker.network=traefik-public
                - traefik.constraint-label=traefik-public
                - traefik.http.routers.jenkins-http.rule=Host(`jenkins.herman.team`)
                - traefik.http.routers.jenkins-http.entrypoints=http
                - traefik.http.routers.jenkins-http.middlewares=https-redirect
                - traefik.http.routers.jenkins-https.rule=Host(`jenkins.herman.team`)
                - traefik.http.routers.jenkins-https.entrypoints=https
                - traefik.http.routers.jenkins-https.tls=true
                - traefik.http.routers.jenkins-https.tls.certresolver=le
                - traefik.http.services.jenkins.loadbalancer.server.port=8080
            placement:
                constraints:
                    - node.labels.jenkins.manager == true

volumes:
    jenkins-data:
    docker-certs:
    docker-data:

networks:
    traefik-public:
        external: true
